### ISSUE TITLE
Gather user research through interviews

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#113]
Gather information from past user studies, current user data, new user research, and market research. Collect as much raw, unedited data as possible, which a smaller subset of people will comb through, consider thoroughly, and distill into a refined design.

Another thing we should do is clarify and explicitly state what our target audience is, eg clinicians, researchers, data scientists. What are the primary use cases are we going to support? This ties into making a list of user stories, eg "I'm a clinician with a list of symptoms and I want to get back a list of probable diseases", which is another issue we need to make.

These things should end up in the condensed in a design doc

---

Conduct 1 on 1 interviews to gather feature enhancement requests, overall UX input, and design notes  from each Monarch Lead separately

- [x] Melissa Haendel
- [x] Peter Robinson (scheduled)
- [x] Chris Mungall 
- ~~David Osumi-Sutherland~~
- [x] Damian Smedley (scheduled)

Additional: 
- [x] Val Wood (scheduled)
- [x] Nicole Vasilevsky (scheduled)
- ~~Leigh Carmody~~
- ~~Sue Bello~~
- ~~Lauren Chan~~
- ~~Alex Wagner~~
- ~~Allison Heath~~
- [x] Anne Thessen
- [x] Sabrina Toro
- [x] Alexa Burger

**Comment by putmantime** [comment]
**Please invite Vince to the interview (vince.rubinetti@gmail.com) and he will join if possible**

@vincerubinetti and I came up with a list of questions that we can ask during interviews. Please feel free to add to this.

- What have you traditionally disliked about the Monarch UI?
    - What are specific pain points with using the Monarch UI?
- What have you traditionally liked about the Monarch UI?
- Who is Monarch’s target audience? 
    - Identify the different users/roles
- What are the primary use cases you want Monarch to be able to support? 
    - Identify specific user stories for each role
- How does Monarch compare to other web applications you have used?  
    - Biomedical or any UX you have experience with.
- How do you typically use the Monarch UI when you use it?
- Could you recommend a true Monarch end user for us to interview?
- Without adding any new features, what do you think could be done to improve the existing monarch experience?
- Do you have a wishlist of features you would like to see implemented?

**Comment by monicacecilia** [comment]
We are gathering feedback at https://bit.ly/mi-ui-2021 - the document also contains links to recordings. 

https://docs.google.com/document/d/1KTctXmAvSK-7fkJmXcvbULVCyG5Bn8YCYq2jGe31Hfw/edit

**Comment by vincerubinetti** [comment]
This is as complete as it is likely to be for the foreseeable future.

**Comment by vincerubinetti** [comment]
Market research notes here: https://docs.google.com/document/d/15zSxos9M7d0ri1gn7Rp6TSFVRGJFjMyxwbhxm5R6Ibc/edit

**Comment by vincerubinetti** [comment]
Comment on deleted issue "perform face to face UX testing/feedback on existing monarch app" by Julie:

---

In addition to gathering feature requests and UX feedback per monarch-initiative/monarch-api#113 , face-to-face testing demos could be performed for valuable insight. However this may not be possible for a while due to covid.

Here's what we had proposed previously for what the goal of these face to face sessions should and how they should be conducted.

"User outreach and usability evaluation efforts will drive the development of new features in the Monarch website. Inspection techniques such as heuristic evaluation (assessing adherence to best practices) and cognitive walkthroughs will be used to assess new designs. Think-aloud usability studies at key scientific meetings will provide insight into difficulties that users might encounter. Testing sessions may range from capturing first impressions through Five Seconds tests to completing more complex use-case challenges during Tree Testing and Card Sorting sessions that will assess suitability of our tools for specific problems; these sessions will also include Moderated and Unmoderated tests, which quantitatively and qualitatively characterize the user’s interaction with the site. Our goal is to rapidly feed back any problems identified with user experience into site modifications. "
