### ISSUE TITLE
Add support for entity association tables

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#12]
const url = `${biolink}/bioentity/${nodeCategory}/${nodeId}/${getAssociationEndpoint(assocationCategory)}`;
  const response = await request<_Associations>(url, params);

**Comment by kevinschaper** [comment]
Taking this older issue over, the association table on the entity page needs more features than we're providing from the regular associations endpoint. 

The endpoint needs search and sort functionality, and needs to provide directional information to the UI for each association so that the UI can draw association arrows when flipping associations for display

**Comment by kevinschaper** [comment]
Closed by #163
