### ISSUE TITLE
endpoint: node-hierarchy 

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#14]
const url = `${biolink}/graph/edges/from/${id}`;
const response = await request<_Hierarchy>(url, params);
const { nodes, edges } = response;

**Comment by kevinschaper** [comment]
This is used to feed the neighborhood section of the current monarch UI, and for the new UI, we should move to a flatter simplified format for the hierarchy section. 

https://monarch-ui-new.monarchinitiative.org/disease/MONDO:0007947?associations=phenotype#hierarchy

Since it's just rendered as 3 lists, we should just return it that way. Maybe as a dictionary with `super-classes` `equivalent-classes` and `sub-classes` as keys, and then each entry is a dictionary with an id and a label?

Maybe `/entity/{id}/hierarchy` as the url of the endpoint?

**Comment by putmantime** [comment]
- [x] Define the data model for the hierarchical view
- [x] Implement  API endpoint

The model will be a Neighborhood class with 3 lists of associations (e.g. parent, sibling, child)
We could make this more open-ended where you pass it a list of predicates to include in the response.

**Comment by kevinschaper** [comment]
Resolved with #39
