### ISSUE TITLE
Change feedback endpoint from GET url params to POST w/ body

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#150]
Was attempting to submit feedback issue to helpdesk with @cmungall using the feedback form and it hung then threw an error.

**Comment by vincerubinetti** [comment]
@falquaddoomi Can you check if the serverless endpoint is still operational:
https://us-central1-monarch-initiative.cloudfunctions.net/monarch-gh-issue-post

Also nothing changed about the types of params it accepts, right? I see that for some reason we just put the body of the issue right in the URL as a parmeter:

```
https://us-central1-monarch-initiative.cloudfunctions.net/monarch-gh-issue-post?body=**Name**%0Atest%0A%0A**Email**%0A%0A%0A**GitHub+Username**%0A%0A%0A**Details**%0APage%3A+%2F%0ABrowser%3A+Chrome+112.0.0.0%0ADevice%3A+Apple+Macintosh%0AOS%3A+Mac+OS+10.15.7%0AEngine%3A+Blink+112.0.0.0%0A%0A%0ATest+test+test&title=Feedback+form+-+test+-+Test+test+test
```

**Comment by falquaddoomi** [comment]
@vincerubinetti Thanks for the heads up; it was in fact broken due to one of the machines that I use as an entrypoint to the Monarch services changing its IP. This caused a redis instance I'm using to throttle how quickly people can submit feedback to become inaccessible to the function, causing it to fail. I've since updated the DNS entry I'm using to point to that machine and verified that its address is reserved. I just tested it after the change and it seems to be working, but feel free to test it, too.

Regarding the function, I haven't changed it since we set it up. If you'd like, we could revisit how it works, e.g. if you want to POST the feedback body rather than include it as a querystring param.

**Comment by vincerubinetti** [comment]
Thanks! Let's change it to body, but later, once I have time to immediately make the change in the frontend. I'll ping you.

**Comment by vincerubinetti** [comment]
~I don't know when this happened, but the UI code already has this as `POST`, with `title` and `body` in the request body... @falquaddoomi Did the endpoint change to accept post, or has the feedback form just been broken this whole time.~

Ignore above. So it has always been `POST`, but the `title` and `body` are still being passed as url params. I'm going to move them to the request body right now in this PR I'm working on, so please update the endpoint at your convenience.

**Comment by falquaddoomi** [comment]
@vincerubinetti Just FYI, I checked the code and it apparently currently supports the parameters coming from the request body or from the querystring, preferring the body if it's available. Here's the relevant code from the issue-posting method, where `request` is a Flask request object (https://flask.palletsprojects.com/en/latest/api/#flask.Request):

```python
    # ....
    # snippet comes from gh_post_issue()
    request_json = request.get_json()

    try:
        args_set = request_json if request_json else request.args
        title, body = [args_set[x] for x in ('title', 'body')]

        # omitted: the rate limiting check, token retrieval, issue posting

        return (resp.json(), resp.status_code, headers)

    # ...
```

I can change it to just accept it from the body or leave it as-is, your choice.

**Comment by vincerubinetti** [comment]
Oh nice. Doesn't matter to me. We're going to merge and deploy this PR today, so if you wanted to get rid of some of your code later today or next week that'd be fine.
