### ISSUE TITLE
About pages open to middle of page

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#286]
Scrolling to top of page has to be done manually after loading for some reason

**Comment by vincerubinetti** [comment]
This is expected behavior. I don't actually like this behavior, but it is for some reason pretty common across the internet and many people expect it. Many sites like to bring you back to the same position you were at.


See:
https://router.vuejs.org/guide/advanced/scroll-behavior.html

Vue router is supposed to handle this for us. It looks like it only works if you go backward/forward in the browser history, but not with a hard refresh.

Also if you had a hash in your url, e.g. https://monarch-app.monarchinitiative.org/team#semanticly, it would keep going back down to that on any refresh/navigation.
