### ISSUE TITLE
make sure we're getting google analytics data from next.mi.org

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#303]

**Comment by glass-ships** [comment]
hey @vincerubinetti am i correct in remembering you've already handled this?

**Comment by vincerubinetti** [comment]
The google analytics code is [here](https://github.com/monarch-initiative/monarch-app/blob/main/frontend/src/main.ts#L50), I'm not sure if this code is still up to date. Iirc, I don't have access to the monarch google analytics account.

Whether or not analytics (and other tracking) is turned on for any given version/environment.etc is determined [here](https://github.com/monarch-initiative/monarch-app/blob/main/frontend/src/main.ts#L32). Currently it's just on if the url hostname ends with mi.org. So that applies to dev.mi.org, beta, and next. I figured we'd want this, and assumed GA has some way in its interface to discriminate between the subdomains when looking at stats.
