### ISSUE TITLE
Local API search/autocomplete doesn't work

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-app#307]
![image](https://github.com/monarch-initiative/monarch-app/assets/26975530/17ea500c-1d51-4bfe-bc94-9051efb97299)

**Comment by vincerubinetti** [comment]
Problem was I forgot to add `http://` before `127.0.0.1:8000`, so it accidentally became a relative url like `http://localhost:5173/127.0.0.1:8000/v3/api/search`. It doesn't show in the screenshot above because the first "Url" log just logs the url verbatim passed to fetch. Expanding the full `Request` object revealed the error.
