### ISSUE TITLE
Click to copy not working on Safari

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#308]
I'm not sure why this stopped working, I know it was ok in the past, and it's still fine on chrome. 

In the error console, I see: 

```
[Vue warn]: Error in 5: "TypeError: undefined is not an object (evaluating 'window.navigator.clipboard.writeText')"
```

**Comment by vincerubinetti** [comment]
Are you using `https`? Apparently it won't work in unsecured contexts for "security reasons". Related: 

https://stackoverflow.com/questions/57868405/safari-clipboard-error-typeerror-undefined-is-not-an-object
https://developer.apple.com/forums/thread/691873

For me it seems to work on `http` and `localhost`, but maybe they've since added an exception for that since they know developers would be annoyed.

**Comment by vincerubinetti** [comment]
I'll add this to a PR i'm working on with small fixes. It'll at least show an error message if it fails. But I can't do anything to change that behavior.

We should probably be enforcing/redirecting to `https` anyway.
