### ISSUE TITLE
Will you still be able to access model organism phenotypes from human genes?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/monarch-app#326]
**Please describe your question, suggestion, or concern.**

On the current website from a human gene page you can access phenotypes of orthologs in model species. Will this feature be available on the new site?

v

If your question or suggestion is specific to Mondo, please submit it here instead: https://github.com/monarch-initiative/mondo/issues

**Comment by kevinschaper** [comment]
It's still an open question whether we should handle this in the way that the old system did, by having a gene_closure to use when searching against this category specifically, or whether to actually materialize these edges. 

Longer term, I think it would be very cool to export and share phenotype-via-orthology edges in some sort of downloadable format (and as a part of the graph we sent to Translator). 

Nearer term, I think we could probably implement the gene_closure in less time, so maybe that's the right place to start.

**Comment by kevinschaper** [comment]
I'm going to move this issue forward to the February release. 

Part of the decision is whether we should instantiate these associations in the graph as multi-hop shortcuts with a new Biolink category like `biolink:OrthologousGeneToPhenotypicFeature` or add some kind of special handling to our api endpoint so that the gene ID gets looked up in a different field that includes orthologs.  

They both make me a little nervous. 

The API is really best off only working with the data as it exists, and not trying to pretend that edges exist that don't, it will be a bit awkward and error prone to present these along with other associations. On the other hand, I can also imagine that finding multi-hop shortcuts where you didn't expect them could be an unpleasant surprise to data consumers if we actually instantiate the edges. 

The ideal might actually be to make a specific API endpoint for these edges, and serving them in their own section of the UI.

**Comment by kevinschaper** [comment]
As I'm about to bump this forward again, my current proposal for this is that we simply have some kind of `traverse_orthologs` boolean flag on the association table api endpoint that will fetch the entity IDs from the other side of an orthologous_to relationship and feed them into the search, and the associations returned will just be those associations to the orthologs. We can secondarily add a checkbox/toggle on the associations section in the UI as well. The API part is probably a few hours work, and the toggle in the UI shouldn't be much more. 

We could probably make it available in the general associations endpoint, but since an entity argument specifically would be required for it to make sense, we would have to do a custom validation check and error message, which feels like an argument against using that endpoint. 

I also considered whether we should have some sort of generalized two-hop functionality, but I'm not convinced that there is a use case that would justify the potential downside of this kind of manual in-code join becoming a performance problem. If we really want to generalize multi-hop questions, we should have api endpoints that talk to neo4j.
