### ISSUE TITLE
Please let me know whan new gene-disease association downloads are available

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/monarch-app#327]
Please let me know when new gene-disease association downloads are available, Thanks!

**Comment by vincerubinetti** [comment]
Related, you may want to subscribe to this issue: https://github.com/monarch-initiative/monarch-app/issues/57

**Comment by kevinschaper** [comment]
We need to update: https://data.monarchinitiative.org/README.txt - while also using it to drive our new download file generation process

We should look at whether it's practical to support the old file format.

**Comment by ValWood** [comment]
Hi @kevinschaper is there  currently a way  easily get all human gene associations? i.e. API or whatever...we can use a different way.
There's no hurry but we'd like to automate our  disease gene associations  at some point ( CC @kimrutherford).

**Comment by kevinschaper** [comment]
Hi @ValWood,

Our latest development release has tsv output here:
https://data.monarchinitiative.org/monarch-kg-dev/latest/tsv/index.html

and very soon (later today, I think), they should show up at https://data.monarchinitiative.org/monarch-kg/latest/tsv/index.html

The folder layout should match the previous tsv export, but reduced to match the data types we have now. The columns within the files are close, but not exactly the same, since they match Biolink model.

**Comment by ValWood** [comment]
Great thanks, we'll try it soon!
v
