### ISSUE TITLE
Jump to middle of the page on the new UI

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#439]
When you go to a new page on the UI, it jumps to the middle of the page. Even when I clear the cache, it still jumps to the middle. It would be better to land on the top of the pages every time.

**Comment by vincerubinetti** [comment]
This is not a bug, this is intended behavior and standard behavior on many (possibly most) sites. See [scroll restoration](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-restoration-mode). We can remove this behavior but some users may prefer it this way, e.g. clicking on a node association (halfway down the page), going to the new node page, then going back in the history and still being halfway down the page.

**Comment by vincerubinetti** [comment]
To be clear, after testing and investigating further, how this behaves matches browser native behavior. Example: go to a wikipedia page, nav to another page within wikipedia, then go back. It will restore the scroll position, _even if you clear `localStorage`, `sessionStorage`, cache, cookies, etc_. I believe `vue-router` is able to do this via the [history state property](https://developer.mozilla.org/en-US/docs/Web/API/History/state) (basically a hidden arbitrary state object that can be attached to each browser history entry along with the url), which is why nothing to clear it works, aside from opening the same url in a new tab. 

This is a single line of code for us; it's all handled by `vue-router`, to mimic the normal native behavior of browsers when navigating between two static html resources.

In a meeting we've decided to remove this behavior completely (and not do inconsistent, unexpected per-page behavior). But let it be known that we are deviating from standard behavior.

**Comment by sagehrke** [comment]
@amc-corey-cox FYI
