### ISSUE TITLE
FB curie expands to a link that doesn't work

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#452]
https://monarchinitiative.org/FB:FBgn0029157

We're not doing the uri link yet (that's #450), but we have FB:FBgn0029157 in the xrefs section, and it's expanding to `http://identifiers.org/flybase/FBgn0029157`  which links to this lovely bomb 404:

<img width="774" alt="Screenshot 2023-10-27 at 11 09 55 AM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/9479721e-281c-4819-a58f-6e4fb7e16486">

Honestly, I wish we were expanding to http://flybase.org/reports/FBgn0029157

**Comment by sierra-moxon** [comment]
https://identifiers.org/fb:FBgn0011293 does resolve to that FB page, through BioEntity Link (which is the application that Karen Yook and Nathan Dunn were working on, which may still be in production - and probably is because that URL resolution works).  It is not clear to me why that is the default resolution of identifiers.org. 

I am almost 100% sure this entry (and the resolution information) at identifiers.org has changed in the last 3 weeks... 😭

**Comment by kevinschaper** [comment]
This is working now (on both dev and production, since the fix was in curie mapping resources outside of our app)
