### ISSUE TITLE
Feedback form - mentioned but not hyperlinked at the top of home page

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-app#473]
At the very top of monarchinitiative.org, it says
> This web app is the successor to the [old web app here](https://previous.monarchinitiative.org/). Not all features are implemented yet. Please use the feedback form to tell us what you think!

There's a convenient link to the old web app, but no link to the feedback form. It's not hard to find under "Help", but why not make it as easy as possible for users to find by hyperlinking "feedback form" to https://monarchinitiative.org/feedback? (I can do a PR to make that change, if that sounds ok.)

I also noticed that on the Help page, it says
> Feedback Form
Right here, no account required, one-way

but if you go to the feedback form, it says
> Email
So we can follow up with you

so it's NOT one-way, and in fact, lower down, it mentions that using the feedback form creates a public GitHub issue, which is of course two-way.

**Comment by vincerubinetti** [comment]
The feedback form is accessible from any page by the speech bubble icon in the lower right corner. We want to encourage users to use that instead of `/feedback` because it is specific to whatever page the user is currently on. This is the change I will make to address your comment:

<img width="739" alt="Screenshot 2023-11-17 at 12 03 58 PM" src="https://github.com/monarch-initiative/monarch-app/assets/8326331/5921207c-2ddd-4413-9d77-013d9f8d9b0a">

---

> so it's NOT one-way

The name/email/username are **optional**. It is one-way because if you do not enter these things (which is very likely when they are optional), you are sending an issue off to the help desk _without any way to identify your or respond to you_. That is the point of saying one-way, and it should be clear to the user that that is the case.

However since these terms appear to be confusing, I'll remove them and hope users understand the difference between the Feedback Form and Help Desk links on the help page at a glance.
