### ISSUE TITLE
Add dropdown for all major resources listed on the resources page

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-app#501]
When hovering over "Resources", we should see all the resources listed as a dropdown as well.

cc @sagehrke

**Comment by vincerubinetti** [comment]
This would be duplicating the list. It should be either a dropdown, or a separate page listing them.

Also I feel that if we are not disciplined about what goes in the header and keep throwing things in there, this version of the UI will eventually become the same overpopulated header that v2.0 had, which people had trouble navigating and finding things in.

**Comment by sagehrke** [comment]
I like the idea of having a dropdown for resources, with each Flagship resource having a page. **However, this is not something we need to worry about right now.** This will be a bigger website alignment push that will take more coordination across the Monarch ecosystem and not just a simple upgrade on the website. 

Please note, that this eventual upgrade would not be adding content to the header, it would simply be changing how the header behaves - going to a page vs having a dropdown to other pages. 

@vincerubinetti your concern about the header clutter has been noted. I don't think we plan to add any more header content any time soon, however, the Resources button was necessary and I am glad it is there! It looks great! Thank you for all your work on the UI! It is really appreciated by everyone on the team. 

Let's keep this ticket open so we don't forget about this idea, but it can remain unassigned for now.

**Comment by vincerubinetti** [comment]
Yes, to be clear, I just don't want to have it BOTH be a dropdown of external link and a dedicated `/resources` page with all/some of the same links, because that will be very prone to getting out of sync, and moreover I think many users will know one method exists and not the other (more likely, they'll not know they could click on the "Resources" link itself to go to the page and get more info).

More generally, I want to emphasize that I'm not trying to discourage any ideas, I'm only trying to make sure the right questions are being considered and that things stay consistent and manageable.

**Comment by sagehrke** [comment]
Addressed in #735
