### ISSUE TITLE
Text annotator labels 'patients' with mouse gene

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#544]
This is a good test case for starting to tighten up the precision on our grounding, in the example text `patients` matches against [MGI:1332635](https://monarchinitiative.org/MGI:1332635), because of the synonym / previous gene name `nuclear localization signal protein absent in velo-cardio-facial patients` 
<img width="436" alt="Screenshot 2024-01-19 at 11 36 04 AM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/a9672d6f-795d-4840-b8d7-9c34054423f5">

I'm not sure if it's something that we can build out of lucene query syntax (use phrase searching?), or if we might end up needing to search against a field that keeps doesn't tokenize as much.

**Comment by kevinschaper** [comment]
More examples of the same substring problem from @cmungall :

![image_720](https://github.com/monarch-initiative/monarch-app/assets/4535019/f4d80f0a-c5d3-407d-a408-e6e5bed0cdc1)
![image_720](https://github.com/monarch-initiative/monarch-app/assets/4535019/789cf105-00a0-4788-a9f9-3e81369a11a7)

**Comment by madanucd** [comment]
The exact match of recognized entities in Solr addresses substring issues. Terms like "patients," "function," "kindred," and "prominent" are excluded from annotation. However, errors may occur, such as "reduced" being annotated as the "PoID3" gene due to its synonym association. A pattern-based approach utilizing dependency parsing aids in identifying names of authors or people, such as Lewis, Bard, and Morell, which are then excluded from annotation.

To address these issues, the following pull requests (PRs) have been implemented:

Increase grounding precision: [PR #565](https://github.com/monarch-initiative/monarch-app/pull/565)
Handle inconsistent annotations: [PR #574](https://github.com/monarch-initiative/monarch-app/pull/574)
