### ISSUE TITLE
Add NCBI to Pombase Gene Mapping to Monarch Mapping Commons using NCBI Gene file

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-app#571]
It is not obvious where to get this mapping from.
@valwood do you have suggestions for where we could find these mappings?

**Comment by ValWood** [comment]
Hi @putmantime I don't know if one is available- we have never been asked for it. We only maintain PomBase-> UniProt, so if you can get from Uniprot to NCBI you can do it that way.

Or maybe there is a web service where you can retrieve it with the systematic ID?
since:
https://www.ncbi.nlm.nih.gov/gene/?term=SPBC11B10.09

or, if Monarch  uses DIOPT at all for ortholog calls, DIOPT includes the fission yeast NCBI gene identifier so you could get it from this data

**Comment by monicacecilia** [comment]
Hi @kevinschaper - could I kindly ask for an update on the status of these mappings? 
Have we now found an alternative way to solve it? Or are we still hoping to find a solution? 
If the latter, let's please find a new assignee (not you) to work on this. And let's bring it up in the next data call on 2024-02-01.
Thank you!

@sagehrke 👀 👆🏽

**Comment by kevinschaper** [comment]
Val's suggestion was perfect, we can use NCBI's gene_info.gz  (which I think may already be used in the mapping repo). 

Being unix-y about it rather than pandas-y, this uses the GeneID and LocusTag columns:
```
gzcat gene_info.gz | grep ^4896 | cut -f 2,4 | sed 's@^@NCBIGene:@' | sed 's@\t@\tPomBase:@' | head -5
NCBIGene:1669496	PomBase:ScpofMr11
NCBIGene:1669497	PomBase:ScpofMt13
NCBIGene:1669498	PomBase:ScpofMt14
NCBIGene:1669499	PomBase:ScpofMt15
NCBIGene:1669500	PomBase:ScpofMr12
``` 

I'll move this issue over to monarch-app so that we can put it into a milestone

**Comment by ValWood** [comment]
These Ids "PomBase:ScpofMr11" etc
aren't PomBase IDs?

**Comment by ValWood** [comment]
If used my suggestiion these from DIOPT, maybe DIOPT  roll their own IDs? I have never seen these. But I assume the actual PomBAse Ids are also there?

**Comment by kevinschaper** [comment]
Oh, I see what you mean - I picked a PomBase gene ID and made sure it was present, but didn't look at what other records NCBI has for taxid 4896. Here's an example of one of those: https://www.ncbi.nlm.nih.gov/gene/?term=1669520

Ultimately, a 3rd party association record that comes in with `NCBIGene:1669520` that we erroneously map to `PomBase:ScpofMt35` would be dropped from the graph because it can't connect to anything that PomBase says is a gene, but in as much as the mapping files are a data product of their own, we need to avoid producing fake PomBase curies!

**Comment by kevinschaper** [comment]
I took the first suggestion of retrieving from Entrez gene. It feels a little strange to pull ID mappings from DIOPT when we aren't getting their orthology (yet?), but that might be a better choice if it avoids having to secondarily filter down with information from an additional file.

**Comment by ValWood** [comment]
Right these are mitochondrial genes, it is possible a 3rd party submitted a version of the mitochondrial genome with non-conventional IDs. I will look into it.
Hopefully most are OK.

**Comment by matentzn** [comment]
Wherever it comes from, the good idea would be to add it to our mapping commons and add provenance to the mapping.

**Comment by monicacecilia** [comment]
@kevinschaper ping! 🎉

**Comment by kevinschaper** [comment]
They're in and working!

**Comment by ValWood** [comment]
Excellent!
