### ISSUE TITLE
Add option to supply a metric for phenotype comparative search

### ISSUE THREAD

**Issue by dominickdm** [monarch-initiative/monarch-app#593]
Hello,

Our application is using 3 main API calls.
The first one is easy to migrate, but for the second and third, we are not sure what's the successor of this call. Can you please assist and tell us what new API call we should use?

https://api-biolink.monarchinitiative.org/api/bioentity/phenotype/HP:0012773

https://api-biolink.monarchinitiative.org/api/sim/search?taxon=9606&metric=phenodigm&limit=20&&id=HP:0012773
* note: metric can be 'phenodigm, jaccard, simGIC, resnik or symmetric_resnik'

https://api-biolink.monarchinitiative.org/api/bioentity/disease/MONDO:0014032/genes?use_compact_associations=true

**Comment by dominickdm** [comment]
Dear,

Please have a look. March 20, 2024 is a very tight deadline..
(source of deadline: https://monarchinit.medium.com/migrating-to-the-new-monarch-infrastructure-fe9d98ccf64a)

**Comment by kevinschaper** [comment]
Hi @dominickdm, thanks for creating the issue, and I apologize for the short timeline. 

I think you probably already had the first two solved:
https://api-v3.monarchinitiative.org/v3/api/entity/HP:0012773
https://api-v3.monarchinitiative.org/v3/api/semsim/search/HP%3A0012773/Human%20Genes?limit=10  (I think the final ranking is by phenodigm score, and we don't have the option to choose a different option now, but I think we could probably add it back)

I agree that `disease/<MONDO ID>/gene` is a little bit of a less obvious mapping.

It's possible by specifying association categories or predicates, `biolink:CorrelatedGeneToDiseaseAssociation` , `biolink:CausalGeneToDiseaseAssociation` would be the categories:

https://api-v3.monarchinitiative.org/v3/api/association?object=MONDO:0014032&category=biolink:CorrelatedGeneToDiseaseAssociation&category=biolink:CausalGeneToDiseaseAssociation

It can also be done with predicates
https://api-v3.monarchinitiative.org/v3/api/association?object=MONDO:0014032&predicate=biolink:gene_associated_with_condition&predicate=biolink:causes&predicate=biolink:contributes_to

Finally, we have a new release coming in the next week which really is probably the most direct mapping, being able to specify the subject_category and object_category, on the dev API that looks like:

http://api-dev.monarchinitiative.org/v3/api/association?subject_category=biolink:Gene&object=MONDO:0014032

We don't yet have the compact_association flag, but I'm realizing now that we really should add it, so I'll make an additional issue so that we can get that into our March release.

**Comment by dominickdm** [comment]
HI @kevinschaper 
Thank you for your feedback! I'll have a closer look (compare the output of both API's) in one of the coming days.

**Comment by davudkurbanov** [comment]
Hi @kevinschaper 
I have investigated this migration further and have some questions.

We have been using following endpoint of API V2, to retrieve list of diseases: 
    https://api-biolink.monarchinitiative.org/api/sim/search?taxon=9606&metric=phenodigm&limit=20&&id=HP:0012773
    
With following response:
    ![image](https://github.com/monarch-initiative/monarch-app/assets/55686942/f489088e-d5d9-4d70-a7b3-33259d458cc2)
    *Marked properties are used by our application*
    
For API V3 you have suggested to make use of:
    https://api-v3.monarchinitiative.org/v3/api/semsim/search/HP%3A0012773/Human%20Genes?limit=10
Response:
    ![image](https://github.com/monarch-initiative/monarch-app/assets/55686942/7d26ea79-f7c5-41cc-93f0-5ccb6bd2154e)
    

This returns genes, so I suppose for the diseases, we should make use of:
    https://api-v3.monarchinitiative.org/v3/api/semsim/search/HP%3A0012773/Human%20Diseases?limit=10

Response:
    ![image](https://github.com/monarch-initiative/monarch-app/assets/55686942/9b2e1943-811c-4f36-8ec4-8c2c0bed8ef9)
    
However, the response does not seem to have the same result as from API V2. 
 * Is this because the default metric is not 'phenodigm'? 
 * How can we achieve the same result as in API V2?
     
Also, do you have any information on whether the 'metric' query parameter will be added to the endpoint above? If so, could you give us a rough estimate? 

Edit: the same question for the 'taxon' parameter => would this be added to the last mentioned by me endpoint? If so, could you give us a rough estimate?

**Comment by Lava9050** [comment]
Hello @kevinschaper, any news on the backwards incompatibility issues mentioned above? 
Thanks in advance for your replies!

**Comment by kevinschaper** [comment]
Hi @davudkurbanov and @Lava9050 

I had a chance to look this over with the Semsimian developers today (I'll tag them in as well, @hrshdhgd, @justaddcoffee, @caufieldjh)

We don't expect the same results, even given the same ranking method. The old API is frozen with data from 2021, and we would expect new annotations to change the results for that reason alone. Additionally, the structure of Phenio differs from the structure of the former Monarch Ontology, which will also affect the results. 

I was able to confirm that the current method used is resnik, rather than the former default of phenodigm. I'm discussing with the algorithms team and Monarch leadership the priority of offering alternative ranking methods.

**Comment by davudkurbanov** [comment]
Hi @kevinschaper 

Thank you for the response!
At current time we were able to complete most of the migration.

This explains why I had different results during comparison-testing of 2 API versions.
> We don't expect the same results, even given the same ranking method. The old API is frozen with data from 2021, and we would expect new annotations to change the results for that reason alone. Additionally, the structure of Phenio differs from the structure of the former Monarch Ontology, which will also affect the results.

I have interpreted that the ranking from API V2 was determined by score (?) and was able to reflect this in code, but only based on the *resnik* metric/ranking. It would be indeed handy if we could have alternatives.
> I'm discussing with the algorithms team and Monarch leadership the priority of offering alternative ranking methods.

**Comment by monicacecilia** [comment]
UPDATES: 
Needs: 
- Metric to be deployed
- New Semsim server build
- Feedback needed
- Work on PR is ongoing 
- Next up: Discuss during A&A call

@kevinschaper @glass-ships @hrshdhgd @justaddcoffee 👀 ⬆️
