### ISSUE TITLE
Switch node page to using entity api endpoint

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#70]
The new [entity endpoint](https://github.com/monarch-initiative/monarch-api/blob/main/frontend/src/api/entity.ts) includes the basic details and neighborhood, and will eventually also include association counts. 

An example fixture is there already: https://github.com/monarch-initiative/monarch-api/blob/main/frontend/tests/fixtures/entity.json, and it's answering at http://api-dev.monarchinitiative.org/api/entity/MONDO:0005439

The schema documentation page for the response is: https://monarch-app.monarchinitiative.org/docs/Data-Model/Node/

(I just noticed some weird naming, that we have an Entity endpoint, which returns the schema for a class called Node, which inherits from an Entity - adding the extras needed for the page over the basic details - probably fine to stick with for now but it is a little odd)

**Comment by glass-ships** [comment]
> (I just noticed some weird naming, that we have an Entity endpoint, which returns the schema for a class called Node, which inherits from an Entity - adding the extras needed for the page over the basic details - probably fine to stick with for now but it is a little odd)

i've been thinking about this more lately, part of me thinks we should actually stick with the old `node-<module>.ts` naming scheme for clarity and replace the old files/rename to `node-module-old.ts` or something

**Comment by vincerubinetti** [comment]
Going forward, when we switch over a biolink endpoint to a monarch endpoint, let's just replace the `/api` code. No need for `-old` anything, that's what git's for, and we'd end up with tons of cruft that never gets deleted because people are afraid to delete it because they don't know if it'll break something.

e.g. node-search.ts and search.ts don't need to simultaneously stick around. And a tagent: in that particular example, I think node-search is less ambiguous, as there are other searches on the site like in the phenotype explorer. For now I'd like to keep the same naming schema, unless some terminology has fundamentally changed in the backend. I've tried to keep comments, file naming, etc. all consistent terminology, and I'm afraid just renaming files will let something get out of sync.

**Comment by kevinschaper** [comment]
This is done
