### ISSUE TITLE
Duplicate HPO entries

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-app#787]
It looks like the entry for Marfan syndrome has numerous duplicated entries, e.g., Scoliosis

https://monarchinitiative.org/MONDO:0007947

It  would be better for the API to take this information from the HPO API and have one source of truth.

**Comment by sagehrke** [comment]
Hi @pnrobinson, 
Thanks for this ticket. This is now fixed. The issue was the Source was not showing up on the Disease to Phenotype table. The team has now added this as a column so you can see the difference. For example, Scoliosis now is listed twice but it shows one is from OMIM and one is from Orphanet. 
![Screenshot 2024-11-01 at 12 04 42 PM](https://github.com/user-attachments/assets/5e9cba54-ff18-476e-86f0-0264ed4c27cf)

The discussion around when to collapse associations is ongoing.
